apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jiaen04/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: campus-secret
                  key: DATABASE_URL
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: campus-secret
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: campus-secret
                  key: SUPABASE_KEY
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
